include ../../global_config

OBJS = $(OBJDIR)/normalize.o  \
	$(OBJDIR)/normalizewindow.o

OUTPUT = ../$(OBJDIR)/normalize.plugin

include ../../plugin_config


$(OBJDIR)/normalize.o: normalize.C
$(OBJDIR)/normalizewindow.o: normalizewindow.C
