include ../../global_config

OBJS = ../parametric/$(OBJDIR)/fourier.o \
	$(OBJDIR)/timestretch.o \
	$(OBJDIR)/timestretchengine.o

OUTPUT = ../$(OBJDIR)/timestretch.plugin

include ../../plugin_config




$(OBJDIR)/timestretch.o: timestretch.C
$(OBJDIR)/timestretchengine.o: timestretchengine.C

