include ../../global_config

OBJS = ../colors/$(OBJDIR)/plugincolors.o \
	$(OBJDIR)/chromakey.o

OUTPUT = ../$(OBJDIR)/chromakey.plugin

include ../../plugin_config

$(OBJDIR)/chromakey.o: chromakey.C
