include ../../global_config

OBJS = ../colors/$(OBJDIR)/plugincolors.o \
	$(OBJDIR)/videoscope.o

OUTPUT = ../$(OBJDIR)/videoscope.plugin

include ../../plugin_config


$(OBJDIR)/videoscope.o: videoscope.C
