include ../../global_config

OBJS = 	$(OBJDIR)/translate.o  \
	$(OBJDIR)/translatewin.o

OUTPUT = ../$(OBJDIR)/translate.plugin

include ../../plugin_config

$(OBJDIR)/translate.o: translate.C
$(OBJDIR)/translatewin.o: translatewin.C
