// SPDX-License-Identifier: GPL-2.0-or-later

// This file is a part of Cinelerra-CVE
// Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>

#ifndef HISTOGRAMENGINE_INC
#define HISTOGRAMENGINE_INC

// Number of slots
#define HISTOGRAM_RANGE 0x13333

// Range
#define HISTOGRAM_MIN -0.1
#define HISTOGRAM_MAX 1.1

class HistogramPackage;
class HistogramUnit;
class HistogramEngine;

#endif
