include ../../global_config

OBJS := \
	../colors/$(OBJDIR)/plugincolors.o \
	$(OBJDIR)/histogramengine.o \
	$(OBJDIR)/threshold.o \
	$(OBJDIR)/thresholdwindow.o

OUTPUT := ../$(OBJDIR)/threshold.plugin


include ../../plugin_config



$(OBJDIR)/threshold.o:        threshold.C
$(OBJDIR)/thresholdwindow.o:  thresholdwindow.C
$(OBJDIR)/histogramengine.o:  histogramengine.C




