include ../../global_config

OBJS = \
	../colors/$(OBJDIR)/colorpicker.o \
	$(OBJDIR)/gradient.o \
	../colors/$(OBJDIR)/plugincolors.o

OUTPUT = ../$(OBJDIR)/gradient.plugin

include ../../plugin_config

$(OBJDIR)/gradient.o: gradient.C
