include ../../global_config

OBJS = $(OBJDIR)/fourier.o \
	$(OBJDIR)/parametric.o

OUTPUT = ../$(OBJDIR)/parametric.plugin

include ../../plugin_config


$(OBJDIR)/fourier.o: fourier.C
$(OBJDIR)/parametric.o: parametric.C
