include ../../global_config

OBJS := $(OBJDIR)/interpolateaudio.o


OUTPUT := ../$(OBJDIR)/interpolateaudio.plugin

include ../../plugin_config


$(OBJDIR)/interpolateaudio.o: interpolateaudio.C












