
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 * 
 */

#ifndef SYNTHWINDOW_INC
#define SYNTHWINDOW_INC



class SynthThread;
class SynthOscGUI;
class SynthOscGUILevel;
class SynthOscGUIPhase;
class SynthOscGUIFreq;
class SynthWindow;
class SynthFreqPot;
class SynthCanvas;
class SynthWaveForm;
class SynthBaseFreq;
class SynthMenu;
class SynthClear;
class SynthSubWindow;
class SynthScroll;
class SynthClear;

#define OSCILLATORHEIGHT 40


#endif
