include ../../global_config

OBJS = $(OBJDIR)/linearize.o  \
	$(OBJDIR)/linearizewindow.o \
	../colors/$(OBJDIR)/plugincolors.o

OUTPUT = ../$(OBJDIR)/linearize.plugin

include ../../plugin_config

$(OBJDIR)/linearize.o: linearize.C
$(OBJDIR)/linearizewindow.o: linearizewindow.C
