include ../../global_config

OBJS = $(OBJDIR)/plugincolors.o \
	$(OBJDIR)/colorpicker.o

all: $(OBJS)

include ../../plugin_config

$(OBJDIR)/plugincolors.o: plugincolors.C
$(OBJDIR)/colorpicker.o: colorpicker.C
