include ../../global_config

OBJS = $(OBJDIR)/despike.o  \
	$(OBJDIR)/despikewindow.o

OUTPUT = ../$(OBJDIR)/despike.plugin

include ../../plugin_config

$(OBJDIR)/despike.o: despike.C
$(OBJDIR)/despikewindow.o: despikewindow.C
