include ../../global_config

OBJS = ../colors/$(OBJDIR)/plugincolors.o \
	$(OBJDIR)/diffkey.o \
	$(OBJDIR)/diffkeywindow.o

OUTPUT = ../$(OBJDIR)/diffkey.plugin

include ../../plugin_config

$(OBJDIR)/diffkey.o: diffkey.C
$(OBJDIR)/diffkeywindow.o: diffkeywindow.C
