/*
** Copyright (C) 2002,2003 Erik de Castro Lopo <erikd@zip.com.au>
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU Lesser General Public License as published by
** the Free Software Foundation; either version 2.1 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU Lesser General Public License for more details.
**
** You should have received a copy of the GNU Lesser General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/

/*
** This is the Win32 version of the file config.h which is autogenerated
** on Unix systems.
*/

#pragma warning (disable : 4244)
#pragma warning (disable : 4761)

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* The number of bytes in a double.  */
#define SIZEOF_DOUBLE 8

/* The number of bytes in a float.  */
#define SIZEOF_FLOAT 4

/* The number of bytes in a int.  */
#define SIZEOF_INT 4

/* The number of bytes in a loff_t.  */
#define SIZEOF_LOFF_T 0

/* The number of bytes in a long.  */
#define SIZEOF_LONG 4

/* The number of bytes in a off64_t.  */
#define SIZEOF_OFF64_T 0

/* The number of bytes in a off_t.  */
#define SIZEOF_OFF_T 4

/* The number of bytes in a short.  */
#define SIZEOF_SHORT 2

/* The number of bytes in a size_t.  */
#define SIZEOF_SIZE_T 4

/* The number of bytes in a void*.  */
#define SIZEOF_VOIDP 4

/* Define if you have the free function.  */
#define HAVE_FREE 1

/* Define if you have the fstat function.  */
#define HAVE_FSTAT 1

/* Define if you have the ftruncate function.  */
#define HAVE_FTRUNCATE 1

/* Define if you have the gmtime function.  */
#define HAVE_GMTIME 1

/* Define if you have the gmtime_r function.  */
/*#undef HAVE_GMTIME_R */

/* Define if you have the lseek function.  */
#define HAVE_LSEEK 1

/* Define if you have the malloc function.  */
#define HAVE_MALLOC 1

/* Define if you have the open function.  */
#define HAVE_OPEN 1

/* Define if you have the read function.  */
#define HAVE_READ 1

/* Define if you have the snprintf function.  */
#define HAVE_SNPRINTF 1

/* Define if you have the vsnprintf function.  */
#define HAVE_VSNPRINTF 1

/* Define if you have the write function.  */
#define HAVE_WRITE 1

/* Define if you have the <dlfcn.h> header file.  */
#define HAVE_DLFCN_H 1

/* Define if you have the <endian.h> header file.  */
#define HAVE_ENDIAN_H 1

/* Define if you have the <stdint.h> header file.  */
#define HAVE_STDINT_H 1

/* Define if you have the m library (-lm).  */
#define HAVE_LIBM 1

/* Name of package */
#define PACKAGE "libsndfile"

/* Version number of package */
#define VERSION "1.0.5"

/* Set to 1 to enable experimental code. */
#define ENABLE_EXPERIMENTAL_CODE 0

/* Set to 1 if the compile is GNU GCC. */
/* #undef COMPILER_IS_GCC */

/* Major version of GCC or 3 otherwise. */
/* #undef GCC_MAJOR_VERSION */

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Define to make fseeko etc. visible, on some hosts. */
/* #undef _LARGEFILE_SOURCE */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Set to long if unknown. */
#define TYPEOF_SF_COUNT_T __int64_t

/* Set to sizeof (long) if unknown. */
#define SIZEOF_SF_COUNT_T 8

/* Target processor is big endian. */
#define CPU_IS_BIG_ENDIAN 0

/* Target processor is little endian. */
#define CPU_IS_LITTLE_ENDIAN 1

/* Define if you have C99's lrint function. */
/* #undef HAVE_LRINT */

/* Define if you have C99's lrintf function. */
/* #undef HAVE_LRINTF */

/* Set to 1 if compiling for Win32 */
#define OS_IS_WIN32 1

