// SPDX-License-Identifier: GPL-2.0-or-later

// This file is a part of Cinelerra-CVE
// Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>

#ifndef EFFECTTV_H
#define EFFECTTV_H

#include "vframe.inc"
#include <stdint.h>

// Environment for EffectTV effects
class EffectTV
{
public:
	EffectTV(int w, int h);
	virtual ~EffectTV();

	void image_set_threshold_y(int threshold);
	unsigned char* image_bgsubtract_y(unsigned char *input,
		int color_model, int bytes_per_line);

	void image_bgset_y(VFrame *frame);
	unsigned char* image_diff_filter(unsigned char *diff);

/*
 * fastrand - fast fake random number generator
 * Warning: The low-order bits of numbers generated by fastrand()
 *          are bad as random numbers. For example, fastrand()%4
 *          generates 1,2,3,0,1,2,3,0...
 *          You should use high-order bits.
 */
	static unsigned int fastrand_val;

	static inline unsigned int fastrand()
	{
		return (fastrand_val = fastrand_val * 1103515245 + 12345);
	};

	int w;
	int h;

	int y_threshold;

	unsigned char *background;
	unsigned char *diff, *diff2;
};

#endif
