#! /usr/bin/perl -w
use strict;

my $command = "-felf";
foreach (@ARGV) {
	if (/\.S$/) {
		$command = "gcc " . join(' ', @ARGV);
		last;
	} elsif (/\.s$/) {
		$command = "nasm $command $_";
	} elsif (/^-o$/ || /\.lo$/ || /\.o$/) {
		$command = "$command $_";
	} 
}
print "$command\n";
`$command`;
