include ../../global_config

OBJS = $(OBJDIR)/blur.o  \
	$(OBJDIR)/blurwindow.o

OUTPUT = ../$(OBJDIR)/blur.plugin

include ../../plugin_config

$(OBJDIR)/blur.o: blur.C
$(OBJDIR)/blurwindow.o: blurwindow.C
