#########################################################
#                         LEVEL
#########################################################

include ../../global_config

OBJS = $(OBJDIR)/flip.o \
	$(OBJDIR)/flipwindow.o

OUTPUT = ../$(OBJDIR)/flip.plugin

include ../../plugin_config

$(OBJDIR)/flip.o: flip.C
$(OBJDIR)/flipwindow.o: flipwindow.C
