include ../../global_config

OBJS = $(OBJDIR)/brightness.o  \
	$(OBJDIR)/brightnesswindow.o \
	../colors/$(OBJDIR)/plugincolors.o

OUTPUT = ../$(OBJDIR)/brightness.plugin

include ../../plugin_config


$(OBJDIR)/brightness.o: brightness.C
$(OBJDIR)/brightnesswindow.o: brightnesswindow.C
