include ../../global_config

OBJS = ../parametric/$(OBJDIR)/fourier.o \
	$(OBJDIR)/graphic.o

OUTPUT = ../$(OBJDIR)/graphic.plugin

include ../../plugin_config


../parametric/$(OBJDIR)/fourier.o: ../parametric/fourier.C
$(OBJDIR)/graphic.o: graphic.C
