include ../../global_config

OBJS = $(OBJDIR)/colorbalance.o  \
	$(OBJDIR)/colorbalancewindow.o \
	../colors/$(OBJDIR)/plugincolors.o

OUTPUT = ../$(OBJDIR)/colorbalance.plugin

include ../../plugin_config

$(OBJDIR)/colorbalance.o: colorbalance.C
$(OBJDIR)/colorbalancewindow.o: colorbalancewindow.C
