include ../../global_config

OBJS = $(OBJDIR)/gain.o  \
	$(OBJDIR)/gainwindow.o

OUTPUT = ../$(OBJDIR)/gain.plugin

include ../../plugin_config

$(OBJDIR)/gain.o: gain.C
$(OBJDIR)/gainwindow.o: gainwindow.C
