include ../../global_config

OBJS = \
	../colors/$(OBJDIR)/plugincolors.o \
	$(OBJDIR)/histogram.o

OUTPUT = ../$(OBJDIR)/histogram.plugin

include ../../plugin_config

$(OBJDIR)/histogram.o: histogram.C
