include ../../global_config

OBJS := \
	$(OBJDIR)/unsharp.o \
	$(OBJDIR)/unsharpwindow.o

OUTPUT := ../$(OBJDIR)/unsharp.plugin

include ../../plugin_config

$(OBJDIR)/unsharp.o: unsharp.C
$(OBJDIR)/unsharpwindow.o: unsharpwindow.C
