include ../../global_config

OBJS = $(OBJDIR)/sharpen.o  \
	$(OBJDIR)/sharpenwindow.o

OUTPUT = ../$(OBJDIR)/sharpen.plugin

include ../../plugin_config

$(OBJDIR)/sharpen.o: sharpen.C
$(OBJDIR)/sharpenwindow.o: sharpenwindow.C
