include ../../global_config

OBJS = $(OBJDIR)/deinterlace.o  \
	$(OBJDIR)/deinterwindow.o

OUTPUT = ../$(OBJDIR)/deinterlace.plugin

include ../../plugin_config

$(OBJDIR)/deinterlace.o: deinterlace.C
$(OBJDIR)/deinterwindow.o: deinterwindow.C



