// SPDX-License-Identifier: GPL-2.0-or-later

// This file is a part of Cinelerra-CVE
// Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>

#ifndef BCFILEBOX_INC
#define BCFILEBOX_INC

class BC_FileBox;

// Display modes
#define FILEBOX_LIST    0
#define FILEBOX_ICONS   1

#define FILEBOX_COLUMNS 4

// Column definitions
#define FILEBOX_NAME 0
#define FILEBOX_SIZE 1
#define FILEBOX_DATE 2
#define FILEBOX_EXTENSION 3

#define FILEBOX_HISTORY_SIZE 16

#endif
