#ifndef BCFILEBOX_INC
#define BCFILEBOX_INC

class BC_FileBox;


// Display modes
#define FILEBOX_LIST    0
#define FILEBOX_ICONS   1


#define FILEBOX_COLUMNS 4
//#define DIRBOX_COLUMNS 2

// Column definitions
#define FILEBOX_NAME 0
#define FILEBOX_SIZE 1
#define FILEBOX_DATE 2
#define FILEBOX_EXTENSION 3

#define FILEBOX_NAME_TEXT _("File")
#define FILEBOX_SIZE_TEXT _("Size")
#define FILEBOX_DATE_TEXT _("Date")
#define FILEBOX_EXTENSION_TEXT _("Ext.")
#define FILEBOX_HISTORY_SIZE 16

#endif
