#ifndef BCLISTBOX_INC
#define BCLISTBOX_INC

// Selection mode
#define LISTBOX_SINGLE   0      // Single selection
#define LISTBOX_MULTIPLE 1      // Multiple selections

// Display format
#define LISTBOX_TEXT     0
#define LISTBOX_ICONS    1

// Icon position
#define ICON_LEFT        0
#define ICON_TOP         1

#define LISTBOX_MARGIN   4
#define LISTBOX_BORDER   2
#define ICON_MARGIN      1

class BC_ListBoxItem;
class BC_ListBox;

#endif
