#ifndef BCRESOURCES_INC
#define BCRESOURCES_INC


class BC_Resources;

#define TOTAL_ICONS 5
#define TOTAL_SUFFIXES 7

// Icon types for each list item
#define ICON_FOLDER      0      // Private bitmap
#define ICON_UNKNOWN     1      // Private bitmap
#define ICON_FILM        2      // Private bitmap
#define ICON_SOUND       3      // Private bitmap
#define ICON_COLUMN      4      // Private bitmap

#endif
