
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 * 
 */

#ifndef BCRESOURCES_INC
#define BCRESOURCES_INC


class BC_Resources;

#define TOTAL_ICONS 5
#define TOTAL_SUFFIXES 7

// Icon types for each list item
#define ICON_FOLDER      0      // Private bitmap
#define ICON_UNKNOWN     1      // Private bitmap
#define ICON_FILM        2      // Private bitmap
#define ICON_SOUND       3      // Private bitmap
#define ICON_COLUMN      4      // Private bitmap

#endif
