// SPDX-License-Identifier: GPL-2.0-or-later

// This file is a part of Cinelerra-CVE
// Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>

#ifndef BCRESOURCES_INC
#define BCRESOURCES_INC

class BC_Resources;

#define TOTAL_ICONS 5

// Length of language and region buffer
// Assuming max length of both strings 3
#define LEN_LANG 4
// Length of encoding
#define LEN_ENCOD 64

// Icon types for each list item
#define ICON_FOLDER      0      // Private bitmap
#define ICON_UNKNOWN     1      // Private bitmap
#define ICON_FILM        2      // Private bitmap
#define ICON_SOUND       3      // Private bitmap
#define ICON_COLUMN      4      // Private bitmap

#endif
