// SPDX-License-Identifier: GPL-2.0-or-later

// This file is a part of Cinelerra-CVE
// Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>

#ifndef BC_WINDOWBASE_INC
#define BC_WINDOWBASE_INC

class BC_WindowBase;
class BC_WindowList;
#define BCTEXTLEN 1024
// Milliseconds before cursor disappears during video playback
#define VIDEO_CURSOR_TIMEOUT 2000

// Window options
#define WINDOW_SPLASH  0x80
#define WINDOW_UTF8    0x01

#endif
