include ../../global_config

OBJS = ../parametric/$(OBJDIR)/fourier.o \
	$(OBJDIR)/spectrogram.o

OUTPUT = ../$(OBJDIR)/spectrogram.plugin

include ../../plugin_config




$(OBJDIR)/spectrogram.o: spectrogram.C
