// SPDX-License-Identifier: GPL-2.0-or-later

// This file is a part of Cinelerra-CVE
// Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>

#ifndef OVERLAYFRAME_INC
#define OVERLAYFRAME_INC

// Modes

#define TRANSFER_TYPES 7

#define TRANSFER_NORMAL       0
#define TRANSFER_ADDITION     1
#define TRANSFER_SUBTRACT     2
#define TRANSFER_MULTIPLY     3
#define TRANSFER_DIVIDE       4
#define TRANSFER_REPLACE      5
#define TRANSFER_MAX          6

class OverlayFrame;

#endif
