// SPDX-License-Identifier: GPL-2.0-or-later

// This file is a part of Cinelerra-CVE
// Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>

#ifndef PLAYTRANSPORT_INC
#define PLAYTRANSPORT_INC

class PlayTransport;
class PTransportButton;
class PlayButton;
class FramePlayButton;
class ReverseButton;
class FrameReverseButton;
class FastReverseButton;
class FastPlayButton;
class RewindButton;
class StopButton;
class EndButton;

#endif
