
/*
 * CINELERRA
 * Copyright (C) 2007 Andraz Tori
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 * 
 */

#ifndef RENDERPROFILES_INC
#define RENDERPROFILES_INC

class RenderProfile;

#define MAX_PROFILES 16
#define RENDERCONFIG_DIR     "renderprofiles"
#define RENDERCONFIG_DFLT    "default"
#define RENDERCONFIG_AEFFECT "audio_effect"
#define RENDERCONFIG_VEFFECT "video_effect"
#define RENDERCONFIG_BATCH   "batchrender"
#define RENDERCONFIG_BRENDER "bkgrender"

#endif
