// SPDX-License-Identifier: GPL-2.0-or-later

// This file is a part of Cinelerra-CVE
// Copyright (C) 2007 Andraz Tori

#ifndef RENDERPROFILES_INC
#define RENDERPROFILES_INC

class RenderProfile;

#define MAX_PROFILES 16
#define RENDERCONFIG_DIR     "renderprofiles"
#define RENDERCONFIG_DFLT    "default"
#define RENDERCONFIG_AEFFECT "audio_effect"
#define RENDERCONFIG_VEFFECT "video_effect"
#define RENDERCONFIG_BATCH   "batchrender"
#define RENDERCONFIG_BRENDER "bkgrender"

#endif
