
/*
 * CINELERRA
 * Copyright (C) 2013 Einar Rünkaru <einarry@smail.ee>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef RULER_INC
#define RULER_INC

// defaults
#define RULER_LENGTH 400
#define RULER_MIN_LENGTH 100

#define RULER_HORIZ 0
#define RULER_VERT  1

class Ruler;

#endif