#ifndef VIEWMENU_INC
#define VIEWMENU_INC

class CameraAutomation;
class FadeAutomation;
class MuteAutomation;
class PanAutomation;
class PlayAutomation;
class PluginAutomation;
class ProjectAutomation;
class ShowEdits;
class ShowKeyframes;
class ShowRenderedOutput;
class ShowTitles;
class ShowTransitions;
class ViewMenu;
class MaskAutomation;
class ModeAutomation;
class CZoomAutomation;
class PZoomAutomation;

#endif
